version: '3'

services:
 redis:
  image: redis:3-alpine
 
 hydra-test:
  build: .
  links:
   - redis
  user: dogfish
  ports:
   - "6510:6510"
  volumes:
   - $PWD/..:/home/dogfish/app
  command: sh ./scripts/hydra-cli-config.sh && sh ./scripts/startup.sh ${NODE_ENV}